name = "b2tocf-cluster"
main = "src/index.ts"
compatibility_date = "2025-11-09"

[observability]
enabled = true

# KV 绑定
[[kv_namespaces]]
binding = "BUCKET_STATE_KV"
id = "ad5050a5e9e44f5c8ebd8738df07b24c"

[vars]
# 默认配置
CACHE_TTL_CONTENT = "86400"
UPLOAD_STRATEGY = "balanced"
MAX_BUCKET_SIZE_GB = "9.8"
S3_VIRTUAL_BUCKET = "virtualbucket"
