# Cloudflare Worker Configuration Example
# Rename this file to wrangler.toml and fill in your details.

name = "b2-download-worker" # Your Worker's name
main = "src/index.ts"
compatibility_date = "2025-10-30"

[vars]
# These are NOT secrets and are safe to commit.
UPLOAD_STRATEGY= "balanced"
MAX_BUCKET_SIZE_GB= "10"
CACHE_TTL_METADATA = "3600"
CACHE_TTL_LIST = "600"
ENABLE_CONTENT_CACHE = "false"
BUCKETS_CONFIG = "fbyigovk:004da538dbf31690000000001:K004Hhot2auADW14QiiM49AFHiiXL5c:s3.us-west-004.backblazeb2.com|lpaotgyf:0041d8ca9ddd8f80000000001:K004mQYJ2BiDutYN766aBV3ykiyqyjg:s3.us-west-004.backblazeb2.com"
VIRTUAL_ACCESS_KEY_ID = "test"
VIRTUAL_SECRET_ACCESS_KEY = ""

# To set secrets, use the command line:
# wrangler secret put B2_BUCKET_NAME
# wrangler secret put B2_S3_ENDPOINT
# wrangler secret put B2_ACCESS_KEY_ID
# wrangler secret put B2_SECRET_APPLICATION_KEY
# wrangler secret put URL_SECRET_KEY

